services:
  docker-django-api:
    restart: "no"
    build: ./app-python
    image: app-python:1
    command: python calculate.py
    volumes:
      - ./app-python:/usr/src/app
      #shared folder for input images, etc. Not needed in this example
      - ./img:/usr/src/img
      #shared folder output images, etc. Not needed in this example
      - ./results:/usr/src/results